### ISSUE TITLE
[1.16.4] Deadly End Phantoms don't spawn in modded end biomes

### ISSUE THREAD

**Issue by BugmanBugman** [Thelnfamous1/Deadly-End-Phantoms#1]
Title. They don't spawn in any of the BYG end biomes, just the 2 vanilla biomes.

**Comment by Thelnfamous1** [comment]
This is not a bug, this is a feature request.

**Comment by BugmanBugman** [comment]
Ah, I wasn’t aware if this was intended by the dev or not

Sent from my iPhone

On Jan 7, 2021, at 10:04 PM, Thelnfamous1 <notifications@github.com> wrote:

﻿

This is not a bug, this is a feature request.

**Comment by Thelnfamous1** [comment]
Will try to add compat for modded end biomes
